services:
  postgres:
    image: postgres:15
    container_name: subscription_postgres
    environment:
      POSTGRES_DB: subscriptiondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    networks:
      - db-network
    restart: always

  app:
    build: .
    container_name: subscription_service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/subscriptiondb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - db-network
    restart: always

networks:
  db-network:
    driver: bridge

volumes:
  pgdata:
